# API
api:
    spotify:
        client-id: cb585fdb4e80447b9c2067ccdf03a34e
        client-secret: 3b115fdfa80e4af09691a7ed79d60af2
        scope: user-read-recently-played,user-read-private,user-read-email,user-top-read,playlist-modify-public,playlist-modify-private,playlist-read-private,playlist-read-collaborative,ugc-image-upload
    matrix:
        access-token: sk.eyJ1IjoiYm9uZGFsb3Zza2l5IiwiYSI6ImNscHU1dmJ6ZDBqaTMya3JsdnJveXNtcmcifQ.D3ddmHf8yMBy7Yv4-9LHSw

# web
spotapp:
    api:
        admin-email: thebndlvsk@gmail.com
    client:
        url: http://localhost:3000

# spring
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/kurs_spotapp
        username: admin
        password: admin
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl: none
    mail:
        host: smtp.gmail.com
        port: 587
        username: bndlvskroma@gmail.com
        password: bvpu edru fumx enso
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

# JWT
jwt:
    provider:
        secret: a3VyczFrdXJzMmt1cnMza3VyczRrdXJzNWt1cnM2a3VyczdrdXJzOGt1cnM5